/**
 * Comprehensive TMDB Movie Dataset
 * Curated with accurate TMDB IDs, cast (heroes/leads), directors, genres, posters, backdrops, ratings, and moods.
 */
const sampleMovies = [
  // --- Christopher Nolan & Epic Cinema ---
  {
    tmdbId: 157336,
    imdbId: 'tt0816692',
    title: 'Interstellar',
    originalTitle: 'Interstellar',
    description: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/rAiYTsqAlzk0OvP5qV2V8iV89wh.jpg',
    releaseDate: '2014-11-05',
    releaseYear: 2014,
    runtime: 169,
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    languages: ['English'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine', 'Matt Damon'],
    rating: 8.7,
    voteCount: 35000,
    popularity: 98,
    category: 'top_rated',
    moods: ['Mind-bending', 'Emotional', 'Exciting'],
  },
  {
    tmdbId: 27205,
    imdbId: 'tt1375666',
    title: 'Inception',
    originalTitle: 'Inception',
    description: 'Cobb, a skilled thief who steals corporate secrets through the use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    releaseDate: '2010-07-15',
    releaseYear: 2010,
    runtime: 148,
    genres: ['Action', 'Sci-Fi', 'Adventure', 'Mystery'],
    languages: ['English', 'Japanese', 'French'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy', 'Ken Watanabe', 'Cillian Murphy'],
    rating: 8.4,
    voteCount: 36000,
    popularity: 95,
    category: 'top_rated',
    moods: ['Mind-bending', 'Exciting', 'Dark'],
  },
  {
    tmdbId: 155,
    imdbId: 'tt0468569',
    title: 'The Dark Knight',
    originalTitle: 'The Dark Knight',
    description: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
    releaseDate: '2008-07-16',
    releaseYear: 2008,
    runtime: 152,
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    languages: ['English'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Michael Caine', 'Gary Oldman', 'Aaron Eckhart', 'Maggie Gyllenhaal'],
    rating: 9.0,
    voteCount: 32000,
    popularity: 97,
    category: 'top_rated',
    moods: ['Dark', 'Exciting', 'Emotional'],
  },
  {
    tmdbId: 872585,
    imdbId: 'tt15398776',
    title: 'Oppenheimer',
    originalTitle: 'Oppenheimer',
    description: "The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    releaseDate: '2023-07-19',
    releaseYear: 2023,
    runtime: 180,
    genres: ['Drama', 'History', 'Biography'],
    languages: ['English', 'German'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh', 'Josh Hartnett'],
    rating: 8.5,
    voteCount: 9500,
    popularity: 94,
    category: 'top_rated',
    moods: ['Dark', 'Emotional', 'Inspirational'],
  },
  {
    tmdbId: 1124,
    imdbId: 'tt0482571',
    title: 'The Prestige',
    originalTitle: 'The Prestige',
    description: 'A mysterious story of two magicians whose intense rivalry leads them on a life-long battle for supremacy -- full of obsession, deceit and jealousy with dangerous and deadly consequences.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bdN3gXu4j2njFpWdGqgZioR82q.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/cT8k0W497eR2m7c7v8NnJzC3vA.jpg',
    releaseDate: '2006-10-19',
    releaseYear: 2006,
    runtime: 130,
    genres: ['Drama', 'Mystery', 'Sci-Fi'],
    languages: ['English'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['Hugh Jackman', 'Christian Bale', 'Michael Caine', 'Scarlett Johansson', 'David Bowie', 'Rebecca Hall'],
    rating: 8.2,
    voteCount: 15500,
    popularity: 87,
    category: 'top_rated',
    moods: ['Mind-bending', 'Dark', 'Exciting'],
  },
  {
    tmdbId: 577922,
    imdbId: 'tt6723592',
    title: 'Tenet',
    originalTitle: 'Tenet',
    description: 'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/wzJRB4MKi3yK138bJSuLHNvOXQU.jpg',
    releaseDate: '2020-08-22',
    releaseYear: 2020,
    runtime: 150,
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    languages: ['English', 'Russian', 'Ukrainian'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['John David Washington', 'Robert Pattinson', 'Elizabeth Debicki', 'Kenneth Branagh', 'Michael Caine'],
    rating: 7.2,
    voteCount: 9400,
    popularity: 83,
    category: 'popular',
    moods: ['Mind-bending', 'Exciting'],
  },

  // --- Denis Villeneuve Masterworks ---
  {
    tmdbId: 438631,
    imdbId: 'tt1160419',
    title: 'Dune',
    originalTitle: 'Dune: Part One',
    description: "Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/eeJjd9JU2iOZ9vgN172nBY54yaR.jpg',
    releaseDate: '2021-09-15',
    releaseYear: 2021,
    runtime: 155,
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    languages: ['English'],
    country: 'USA',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Josh Brolin', 'Zendaya', 'Jason Momoa'],
    rating: 8.0,
    voteCount: 12000,
    popularity: 90,
    category: 'popular',
    moods: ['Mind-bending', 'Exciting', 'Inspirational'],
  },
  {
    tmdbId: 693134,
    imdbId: 'tt15239678',
    title: 'Dune: Part Two',
    originalTitle: 'Dune: Part Two',
    description: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s520b4q.jpg',
    releaseDate: '2024-02-27',
    releaseYear: 2024,
    runtime: 166,
    genres: ['Sci-Fi', 'Adventure', 'Action'],
    languages: ['English'],
    country: 'USA',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem', 'Austin Butler', 'Florence Pugh'],
    rating: 8.6,
    voteCount: 8500,
    popularity: 99,
    category: 'trending',
    moods: ['Exciting', 'Mind-bending', 'Emotional'],
  },
  {
    tmdbId: 335984,
    imdbId: 'tt1856101',
    title: 'Blade Runner 2049',
    originalTitle: 'Blade Runner 2049',
    description: "Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/sAtoMqDVhNDQBc3QJL3RF6hlxGq.jpg',
    releaseDate: '2017-10-04',
    releaseYear: 2017,
    runtime: 164,
    genres: ['Sci-Fi', 'Drama', 'Mystery'],
    languages: ['English'],
    country: 'USA',
    director: 'Denis Villeneuve',
    cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks', 'Robin Wright'],
    rating: 8.1,
    voteCount: 13500,
    popularity: 88,
    category: 'critically_acclaimed',
    moods: ['Mind-bending', 'Dark', 'Emotional'],
  },
  {
    tmdbId: 329865,
    imdbId: 'tt2543164',
    title: 'Arrival',
    originalTitle: 'Arrival',
    description: 'Taking place after alien crafts land around the world, an expert linguist is recruited by the military to determine whether they come in peace or are a threat.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/7k22QOcx4g8Q1vAeV1qU57z9k6q.jpg',
    releaseDate: '2016-11-10',
    releaseYear: 2016,
    runtime: 116,
    genres: ['Drama', 'Sci-Fi', 'Mystery'],
    languages: ['English', 'Mandarin'],
    country: 'USA',
    director: 'Denis Villeneuve',
    cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker', 'Michael Stuhlbarg'],
    rating: 8.0,
    voteCount: 17000,
    popularity: 85,
    category: 'top_rated',
    moods: ['Mind-bending', 'Emotional', 'Inspirational'],
  },
  {
    tmdbId: 273481,
    imdbId: 'tt3397884',
    title: 'Sicario',
    originalTitle: 'Sicario',
    description: 'An idealistic FBI agent is enlisted by a government task force to aid in the escalating war against drugs at the border area between the U.S. and Mexico.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/775089vFh3sZJvJ1C6Pz2Z6wL8C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/btvJ2b8hQf092gO3iW0gKq58tF2.jpg',
    releaseDate: '2015-09-17',
    releaseYear: 2015,
    runtime: 121,
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    languages: ['English', 'Spanish'],
    country: 'USA',
    director: 'Denis Villeneuve',
    cast: ['Emily Blunt', 'Benicio del Toro', 'Josh Brolin', 'Victor Garber', 'Jon Bernthal'],
    rating: 7.8,
    voteCount: 9200,
    popularity: 81,
    category: 'popular',
    moods: ['Dark', 'Exciting'],
  },

  // --- Heroes, Sci-Fi & Blockbuster Legends ---
  {
    tmdbId: 603,
    imdbId: 'tt0133093',
    title: 'The Matrix',
    originalTitle: 'The Matrix',
    description: 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/l4QHerTSbflrqeuMu4PxH7N2wBv.jpg',
    releaseDate: '1999-03-30',
    releaseYear: 1999,
    runtime: 136,
    genres: ['Action', 'Sci-Fi'],
    languages: ['English'],
    country: 'USA',
    director: 'Lana Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving', 'Joe Pantoliano'],
    rating: 8.2,
    voteCount: 25000,
    popularity: 90,
    category: 'top_rated',
    moods: ['Mind-bending', 'Exciting', 'Dark'],
  },
  {
    tmdbId: 245891,
    imdbId: 'tt2911666',
    title: 'John Wick',
    originalTitle: 'John Wick',
    description: 'An ex-hitman comes out of retirement to track down the gangsters that took everything from him.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fZPSMVcKrrZqdr6WmggcrV4p8Kf.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/umC047tiM6yVy1tcSYjKG1D1Biq.jpg',
    releaseDate: '2014-10-22',
    releaseYear: 2014,
    runtime: 101,
    genres: ['Action', 'Thriller'],
    languages: ['English', 'Russian'],
    country: 'USA',
    director: 'Chad Stahelski',
    cast: ['Keanu Reeves', 'Michael Nyqvist', 'Alfie Allen', 'Willem Dafoe', 'John Leguizamo'],
    rating: 7.4,
    voteCount: 19000,
    popularity: 92,
    category: 'popular',
    moods: ['Exciting', 'Dark'],
  },
  {
    tmdbId: 361743,
    imdbId: 'tt1745960',
    title: 'Top Gun: Maverick',
    originalTitle: 'Top Gun: Maverick',
    description: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission that demands the ultimate sacrifice.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
    releaseDate: '2022-05-24',
    releaseYear: 2022,
    runtime: 131,
    genres: ['Action', 'Drama'],
    languages: ['English'],
    country: 'USA',
    director: 'Joseph Kosinski',
    cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm', 'Glen Powell', 'Val Kilmer'],
    rating: 8.3,
    voteCount: 8900,
    popularity: 95,
    category: 'popular',
    moods: ['Exciting', 'Inspirational', 'Emotional'],
  },
  {
    tmdbId: 299534,
    imdbId: 'tt4154796',
    title: 'Avengers: Endgame',
    originalTitle: 'Avengers: Endgame',
    description: 'After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    releaseDate: '2019-04-24',
    releaseYear: 2019,
    runtime: 181,
    genres: ['Adventure', 'Sci-Fi', 'Action'],
    languages: ['English', 'Japanese'],
    country: 'USA',
    director: 'Anthony Russo',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson', 'Jeremy Renner'],
    rating: 8.3,
    voteCount: 25000,
    popularity: 96,
    category: 'top_rated',
    moods: ['Exciting', 'Emotional', 'Inspirational'],
  },
  {
    tmdbId: 1726,
    imdbId: 'tt0371746',
    title: 'Iron Man',
    originalTitle: 'Iron Man',
    description: 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/cyecbURX75d4k6jPuh72lF17Rsg.jpg',
    releaseDate: '2008-04-30',
    releaseYear: 2008,
    runtime: 126,
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    languages: ['English', 'Persian', 'Urdu', 'Arabic'],
    country: 'USA',
    director: 'Jon Favreau',
    cast: ['Robert Downey Jr.', 'Terrence Howard', 'Jeff Bridges', 'Gwyneth Paltrow'],
    rating: 7.6,
    voteCount: 26000,
    popularity: 90,
    category: 'popular',
    moods: ['Exciting', 'Funny'],
  },
  {
    tmdbId: 324857,
    imdbId: 'tt4633694',
    title: 'Spider-Man: Into the Spider-Verse',
    originalTitle: 'Spider-Man: Into the Spider-Verse',
    description: 'Teenager Miles Morales becomes the new Spider-Man and joins other Spider-Heroes from parallel dimensions to stop a threat to all reality.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/uUiId6cG32JSRjT6X1Va97hoNZ2.jpg',
    releaseDate: '2018-12-06',
    releaseYear: 2018,
    runtime: 117,
    genres: ['Animation', 'Action', 'Adventure', 'Sci-Fi'],
    languages: ['English', 'Spanish'],
    country: 'USA',
    director: 'Bob Persichetti',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali', 'Brian Tyree Henry'],
    rating: 8.4,
    voteCount: 15000,
    popularity: 94,
    category: 'top_rated',
    moods: ['Family-friendly', 'Exciting', 'Funny', 'Emotional'],
  },

  // --- Martin Scorsese & Crime Classics ---
  {
    tmdbId: 106646,
    imdbId: 'tt0993846',
    title: 'The Wolf of Wall Street',
    originalTitle: 'The Wolf of Wall Street',
    description: "A New York stockbroker refuses to cooperate in a large securities fraud case that involves corruption on Wall Street, the corporate banking world and mob infiltration.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/kW9LmvYfwc5r7sg1w6SpZ9U0j0k.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/cWUOv3H7YCVdGUMavZe9quTe3m9.jpg',
    releaseDate: '2013-12-25',
    releaseYear: 2013,
    runtime: 180,
    genres: ['Crime', 'Drama', 'Comedy'],
    languages: ['English'],
    country: 'USA',
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie', 'Matthew McConaughey', 'Kyle Chandler'],
    rating: 8.0,
    voteCount: 23000,
    popularity: 93,
    category: 'popular',
    moods: ['Funny', 'Exciting', 'Dark'],
  },
  {
    tmdbId: 11324,
    imdbId: 'tt1130884',
    title: 'Shutter Island',
    originalTitle: 'Shutter Island',
    description: 'World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from Boston\'s Shutter Island Ashecliffe Hospital for the criminally insane.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/4GDy0PHYX3VRXUtwK5ysagvkGQN.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/v55LpZ986c7u8bX1v01nJqX7Vw.jpg',
    releaseDate: '2010-02-14',
    releaseYear: 2010,
    runtime: 138,
    genres: ['Drama', 'Mystery', 'Thriller'],
    languages: ['English', 'German'],
    country: 'USA',
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley', 'Max von Sydow', 'Michelle Williams'],
    rating: 8.2,
    voteCount: 23500,
    popularity: 91,
    category: 'top_rated',
    moods: ['Mind-bending', 'Dark', 'Scary'],
  },
  {
    tmdbId: 1422,
    imdbId: 'tt0407887',
    title: 'The Departed',
    originalTitle: 'The Departed',
    description: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/nT97ifVT2J1yMQmeq20Qblg61T.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/A30J77b5Z4yE6tYhNn0V4J7m1Q.jpg',
    releaseDate: '2006-10-05',
    releaseYear: 2006,
    runtime: 151,
    genres: ['Drama', 'Thriller', 'Crime'],
    languages: ['English', 'Cantonese'],
    country: 'USA',
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson', 'Mark Wahlberg', 'Martin Sheen', 'Vera Farmiga'],
    rating: 8.2,
    voteCount: 14500,
    popularity: 88,
    category: 'top_rated',
    moods: ['Dark', 'Exciting'],
  },
  {
    tmdbId: 238,
    imdbId: 'tt0068646',
    title: 'The Godfather',
    originalTitle: 'The Godfather',
    description: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son steps in.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    releaseDate: '1972-03-14',
    releaseYear: 1972,
    runtime: 175,
    genres: ['Drama', 'Crime'],
    languages: ['English', 'Italian'],
    country: 'USA',
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Robert Duvall', 'Diane Keaton'],
    rating: 8.7,
    voteCount: 20000,
    popularity: 96,
    category: 'top_rated',
    moods: ['Dark', 'Emotional', 'Inspirational'],
  },

  // --- Quentin Tarantino & Stylized Cinema ---
  {
    tmdbId: 680,
    imdbId: 'tt0110912',
    title: 'Pulp Fiction',
    originalTitle: 'Pulp Fiction',
    description: "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    releaseDate: '1994-09-10',
    releaseYear: 1994,
    runtime: 154,
    genres: ['Thriller', 'Crime'],
    languages: ['English', 'Spanish', 'French'],
    country: 'USA',
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman', 'Bruce Willis', 'Ving Rhames'],
    rating: 8.5,
    voteCount: 27000,
    popularity: 91,
    category: 'top_rated',
    moods: ['Exciting', 'Dark', 'Funny'],
  },
  {
    tmdbId: 68718,
    imdbId: 'tt1853728',
    title: 'Django Unchained',
    originalTitle: 'Django Unchained',
    description: 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7oWY8vdWW7thTAnVJ3DyCwJRmm7.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/2oZNmdaOp05AcNTcntCU92vBYio.jpg',
    releaseDate: '2012-12-25',
    releaseYear: 2012,
    runtime: 165,
    genres: ['Drama', 'Western'],
    languages: ['English', 'German', 'French'],
    country: 'USA',
    director: 'Quentin Tarantino',
    cast: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio', 'Kerry Washington', 'Samuel L. Jackson'],
    rating: 8.2,
    voteCount: 25000,
    popularity: 92,
    category: 'top_rated',
    moods: ['Exciting', 'Dark', 'Inspirational'],
  },
  {
    tmdbId: 16869,
    imdbId: 'tt0361748',
    title: 'Inglourious Basterds',
    originalTitle: 'Inglourious Basterds',
    description: 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/8BcqzZ4h3uCg8P6U0wN0s8D8v.jpg',
    releaseDate: '2009-08-19',
    releaseYear: 2009,
    runtime: 153,
    genres: ['Drama', 'Action', 'Thriller', 'War'],
    languages: ['English', 'German', 'French', 'Italian'],
    country: 'USA',
    director: 'Quentin Tarantino',
    cast: ['Brad Pitt', 'Mélanie Laurent', 'Christoph Waltz', 'Eli Roth', 'Michael Fassbender', 'Diane Kruger'],
    rating: 8.2,
    voteCount: 21000,
    popularity: 89,
    category: 'top_rated',
    moods: ['Dark', 'Exciting', 'Funny'],
  },

  // --- David Fincher & Psychological Masterpieces ---
  {
    tmdbId: 550,
    imdbId: 'tt0137523',
    title: 'Fight Club',
    originalTitle: 'Fight Club',
    description: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    releaseDate: '1999-10-15',
    releaseYear: 1999,
    runtime: 139,
    genres: ['Drama', 'Thriller'],
    languages: ['English'],
    country: 'USA',
    director: 'David Fincher',
    cast: ['Edward Norton', 'Brad Pitt', 'Helena Bonham Carter', 'Meat Loaf', 'Jared Leto'],
    rating: 8.4,
    voteCount: 28000,
    popularity: 89,
    category: 'top_rated',
    moods: ['Dark', 'Mind-bending', 'Exciting'],
  },
  {
    tmdbId: 807,
    imdbId: 'tt0114369',
    title: 'Se7en',
    originalTitle: 'Se7en',
    description: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJsk9UO.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/ba4CpFFZgspwErmQcQlsr55i792.jpg',
    releaseDate: '1995-09-22',
    releaseYear: 1995,
    runtime: 127,
    genres: ['Crime', 'Mystery', 'Thriller'],
    languages: ['English'],
    country: 'USA',
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow', 'Kevin Spacey'],
    rating: 8.4,
    voteCount: 20000,
    popularity: 90,
    category: 'top_rated',
    moods: ['Dark', 'Scary', 'Mind-bending'],
  },
  {
    tmdbId: 210577,
    imdbId: 'tt2267998',
    title: 'Gone Girl',
    originalTitle: 'Gone Girl',
    description: 'With his wife\'s disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it\'s suspected that he may not be innocent.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qymaJhucquUwjpKVPS2eb7vRSCn.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/u6e6W04nK5fA2N2K2s8w5Bv1mQ.jpg',
    releaseDate: '2014-10-01',
    releaseYear: 2014,
    runtime: 149,
    genres: ['Mystery', 'Thriller', 'Drama'],
    languages: ['English'],
    country: 'USA',
    director: 'David Fincher',
    cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris', 'Tyler Perry', 'Carrie Coon'],
    rating: 7.9,
    voteCount: 18000,
    popularity: 86,
    category: 'popular',
    moods: ['Dark', 'Mind-bending'],
  },

  // --- International, Japanese Animation & Hidden Gems ---
  {
    tmdbId: 496243,
    imdbId: 'tt6751668',
    title: 'Parasite',
    originalTitle: '기생충',
    description: "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdFiyeQIHQWkv.jpg',
    releaseDate: '2019-05-30',
    releaseYear: 2019,
    runtime: 132,
    genres: ['Comedy', 'Thriller', 'Drama'],
    languages: ['Korean'],
    country: 'South Korea',
    director: 'Bong Joon-ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik', 'Park So-dam'],
    rating: 8.5,
    voteCount: 18000,
    popularity: 92,
    category: 'critically_acclaimed',
    moods: ['Dark', 'Mind-bending', 'Funny'],
  },
  {
    tmdbId: 372058,
    imdbId: 'tt5311514',
    title: 'Your Name.',
    originalTitle: '君の名は。',
    description: 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Their fascination with the other triggers a deep connection.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/q719qXXEzOoYaps6qFsxWa93bu.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/70uipC62aPcfZgH2mUuYq6uK7Z0.jpg',
    releaseDate: '2016-08-26',
    releaseYear: 2016,
    runtime: 106,
    genres: ['Animation', 'Romance', 'Drama', 'Fantasy'],
    languages: ['Japanese'],
    country: 'Japan',
    director: 'Makoto Shinkai',
    cast: ['Ryunosuke Kamiki', 'Mone Kamishiraishi', 'Ryo Narita', 'Aoi Yuki'],
    rating: 8.5,
    voteCount: 11000,
    popularity: 89,
    category: 'top_rated',
    moods: ['Emotional', 'Romantic', 'Relaxing'],
  },
  {
    tmdbId: 129,
    imdbId: 'tt0245429',
    title: 'Spirited Away',
    originalTitle: '千と千尋の神隠し',
    description: 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/393mh2AJ0GYW7COxcqzQgR7vjW.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/mSDsSDwaP3E7dEfUPWy4J0djt4O.jpg',
    releaseDate: '2001-07-20',
    releaseYear: 2001,
    runtime: 125,
    genres: ['Animation', 'Family', 'Fantasy'],
    languages: ['Japanese'],
    country: 'Japan',
    director: 'Hayao Miyazaki',
    cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki', 'Takashi Naito'],
    rating: 8.5,
    voteCount: 16000,
    popularity: 91,
    category: 'top_rated',
    moods: ['Family-friendly', 'Relaxing', 'Inspirational'],
  },
  {
    tmdbId: 264660,
    imdbId: 'tt2872718',
    title: 'Ex Machina',
    originalTitle: 'Ex Machina',
    description: 'Caleb, a coder at the world\'s largest internet company, wins a competition to spend a week at a private mountain retreat belonging to the company\'s reclusive CEO, Nathan. But Caleb learns he will have to participate in a fascinating experiment with a beautiful robot.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/btbSMBHQ4hQAa2uW07wB1U3Qz1C.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/9Xw0I5RV2Zq6Q7Xk0b5yW1Qf6k.jpg',
    releaseDate: '2014-12-16',
    releaseYear: 2014,
    runtime: 108,
    genres: ['Drama', 'Sci-Fi', 'Thriller'],
    languages: ['English'],
    country: 'UK',
    director: 'Alex Garland',
    cast: ['Domhnall Gleeson', 'Alicia Vikander', 'Oscar Isaac', 'Sonoya Mizuno'],
    rating: 7.9,
    voteCount: 13000,
    popularity: 84,
    category: 'hidden_gem',
    moods: ['Mind-bending', 'Dark', 'Emotional'],
  },
  {
    tmdbId: 77,
    imdbId: 'tt0120744',
    title: 'Memento',
    originalTitle: 'Memento',
    description: "Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife's killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/yuNs09hvpHVU1cBTCAk9zxsL2oW.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/tl5qfM95b8s8pP1Y23kXpZ2G8Qz.jpg',
    releaseDate: '2000-10-11',
    releaseYear: 2000,
    runtime: 113,
    genres: ['Mystery', 'Thriller'],
    languages: ['English'],
    country: 'USA',
    director: 'Christopher Nolan',
    cast: ['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano', 'Mark Boone Junior'],
    rating: 8.2,
    voteCount: 14000,
    popularity: 82,
    category: 'hidden_gem',
    moods: ['Mind-bending', 'Dark', 'Emotional'],
  },
  {
    tmdbId: 546554,
    imdbId: 'tt6263850',
    title: 'Knives Out',
    originalTitle: 'Knives Out',
    description: 'When renowned crime novelist Harlan Thrombey is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc is mysteriously enlisted to investigate.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/Ab8mkHmkYADjU7wQiOkia99GQI.jpg',
    releaseDate: '2019-11-27',
    releaseYear: 2019,
    runtime: 130,
    genres: ['Comedy', 'Mystery', 'Crime'],
    languages: ['English'],
    country: 'USA',
    director: 'Rian Johnson',
    cast: ['Daniel Craig', 'Ana de Armas', 'Chris Evans', 'Jamie Lee Curtis', 'Michael Shannon', 'Toni Collette'],
    rating: 7.9,
    voteCount: 12500,
    popularity: 88,
    category: 'popular',
    moods: ['Funny', 'Mind-bending', 'Exciting'],
  },
];

module.exports = sampleMovies;
