export interface MockStop {
  id: string;
  name: string;
  latitude: number;
  longitude: number;
  timeOffsetMinutes: number;
  crowdLevel: 'low' | 'moderate' | 'high';
  isInterchange?: boolean;
  transfersAvailable?: string[];
}

export interface MockSegment {
  mode: 'bus' | 'metro' | 'train' | 'taxi' | 'walk';
  lineName: string;
  lineColor: string;
  fromStop: string;
  toStop: string;
  durationMinutes: number;
  distanceKm: number;
  fare: number;
  instructions: string;
  crowdLevel: 'low' | 'moderate' | 'high';
  delayMinutes: number;
}

export interface MockRoute {
  id: string;
  routeId: string;
  name: string;
  transportType: 'bus' | 'metro' | 'train' | 'taxi' | 'walk' | 'mixed';
  origin: string;
  destination: string;
  stops: MockStop[];
  segments: MockSegment[];
  distance: number;
  estimatedTime: number;
  fare: number;
  transfers: number;
  walkingTime: number;
  crowdLevel: 'low' | 'moderate' | 'high';
  status: 'on-time' | 'delayed' | 'disrupted' | 'cancelled';
  delayMinutes: number;
  frequencyMinutes: number;
  co2SavedKg: number;
  wheelchairAccessible: boolean;
  airConditioned: boolean;
  summary: string;
  polylinePoints: [number, number][];
  scheduleTimes: string[];
}

export const INITIAL_ROUTES: MockRoute[] = [
  {
    id: 'route-1',
    routeId: 'MTR-BLU-01',
    name: 'Metro Blue Line (Rapid Transit)',
    transportType: 'metro',
    origin: 'Dwarka Sector 21',
    destination: 'Noida Electronic City',
    distance: 28.5,
    estimatedTime: 38,
    fare: 40,
    transfers: 0,
    walkingTime: 4,
    crowdLevel: 'moderate',
    status: 'on-time',
    delayMinutes: 0,
    frequencyMinutes: 4,
    co2SavedKg: 2.8,
    wheelchairAccessible: true,
    airConditioned: true,
    summary: 'Direct direct high-speed metro corridor with air conditioning and dedicated women coach.',
    scheduleTimes: ['07:00 AM', '07:04 AM', '07:08 AM', '07:12 AM', '07:16 AM', '07:20 AM'],
    stops: [
      { id: 's1', name: 'Dwarka Sector 21', latitude: 28.5524, longitude: 77.0583, timeOffsetMinutes: 0, crowdLevel: 'low', isInterchange: true, transfersAvailable: ['Airport Express'] },
      { id: 's2', name: 'Janakpuri West', latitude: 28.6294, longitude: 77.0778, timeOffsetMinutes: 10, crowdLevel: 'moderate', isInterchange: true, transfersAvailable: ['Magenta Line'] },
      { id: 's3', name: 'Rajiv Chowk (Connaught Place)', latitude: 28.6328, longitude: 77.2195, timeOffsetMinutes: 22, crowdLevel: 'high', isInterchange: true, transfersAvailable: ['Yellow Line', 'City Bus Hub'] },
      { id: 's4', name: 'Mandi House', latitude: 28.6258, longitude: 77.2343, timeOffsetMinutes: 26, crowdLevel: 'moderate', isInterchange: true, transfersAvailable: ['Violet Line'] },
      { id: 's5', name: 'Mayur Vihar-I', latitude: 28.6044, longitude: 77.2942, timeOffsetMinutes: 32, crowdLevel: 'moderate', isInterchange: true, transfersAvailable: ['Pink Line'] },
      { id: 's6', name: 'Noida Electronic City', latitude: 28.6277, longitude: 77.3725, timeOffsetMinutes: 38, crowdLevel: 'low' },
    ],
    segments: [
      {
        mode: 'walk',
        lineName: 'Pedestrian Walk',
        lineColor: '#10b981',
        fromStop: 'Origin Entrance',
        toStop: 'Dwarka Platform 1',
        durationMinutes: 4,
        distanceKm: 0.3,
        fare: 0,
        instructions: 'Walk through Concourse Gate 2 to Platform 1',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
      {
        mode: 'metro',
        lineName: 'Blue Line Express',
        lineColor: '#2563eb',
        fromStop: 'Dwarka Sector 21',
        toStop: 'Noida Electronic City',
        durationMinutes: 34,
        distanceKm: 28.2,
        fare: 40,
        instructions: 'Board Blue Line Train towards Noida Electronic City. Alight at destination.',
        crowdLevel: 'moderate',
        delayMinutes: 0,
      },
    ],
    polylinePoints: [
      [28.5524, 77.0583],
      [28.6294, 77.0778],
      [28.6328, 77.2195],
      [28.6258, 77.2343],
      [28.6044, 77.2942],
      [28.6277, 77.3725],
    ],
  },
  {
    id: 'route-2',
    routeId: 'MXD-MTR-BUS-42',
    name: 'Metro Blue Line → Bus Route 42 (Smart Transfer)',
    transportType: 'mixed',
    origin: 'Janakpuri West',
    destination: 'Cyber City Hub',
    distance: 22.4,
    estimatedTime: 35,
    fare: 35,
    transfers: 1,
    walkingTime: 5,
    crowdLevel: 'moderate',
    status: 'delayed',
    delayMinutes: 5,
    frequencyMinutes: 6,
    co2SavedKg: 2.2,
    wheelchairAccessible: true,
    airConditioned: true,
    summary: 'Optimal blend of fast metro transit and connected electric feeder bus.',
    scheduleTimes: ['07:05 AM', '07:15 AM', '07:25 AM', '07:35 AM'],
    stops: [
      { id: 's20', name: 'Janakpuri West', latitude: 28.6294, longitude: 77.0778, timeOffsetMinutes: 0, crowdLevel: 'moderate', isInterchange: true },
      { id: 's21', name: 'Dhaula Kuan Hub', latitude: 28.5921, longitude: 77.1564, timeOffsetMinutes: 16, crowdLevel: 'moderate', isInterchange: true, transfersAvailable: ['Bus Interchange 42'] },
      { id: 's22', name: 'Cyber City Hub', latitude: 28.4986, longitude: 77.0894, timeOffsetMinutes: 35, crowdLevel: 'low' },
    ],
    segments: [
      {
        mode: 'metro',
        lineName: 'Magenta Line',
        lineColor: '#db2777',
        fromStop: 'Janakpuri West',
        toStop: 'Dhaula Kuan Hub',
        durationMinutes: 16,
        distanceKm: 12.0,
        fare: 25,
        instructions: 'Take Magenta Line towards Botanical Garden to Dhaula Kuan.',
        crowdLevel: 'moderate',
        delayMinutes: 0,
      },
      {
        mode: 'walk',
        lineName: 'Skywalk Connector',
        lineColor: '#10b981',
        fromStop: 'Metro Gate 3',
        toStop: 'Bus Bay 4',
        durationMinutes: 4,
        distanceKm: 0.2,
        fare: 0,
        instructions: 'Use travelator skywalk to Bus Bay 4.',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
      {
        mode: 'bus',
        lineName: 'Feeder Bus 42 AC',
        lineColor: '#f59e0b',
        fromStop: 'Dhaula Kuan Hub',
        toStop: 'Cyber City Hub',
        durationMinutes: 15,
        distanceKm: 10.2,
        fare: 10,
        instructions: 'Board Electric Bus 42 towards Cyber Hub.',
        crowdLevel: 'moderate',
        delayMinutes: 5,
      },
    ],
    polylinePoints: [
      [28.6294, 77.0778],
      [28.5921, 77.1564],
      [28.4986, 77.0894],
    ],
  },
  {
    id: 'route-3',
    routeId: 'BUS-EXP-500',
    name: 'City Express Bus 500 (Economy Direct)',
    transportType: 'bus',
    origin: 'Central Station Terminal',
    destination: 'University North Campus',
    distance: 18.2,
    estimatedTime: 45,
    fare: 20,
    transfers: 0,
    walkingTime: 6,
    crowdLevel: 'low',
    status: 'on-time',
    delayMinutes: 0,
    frequencyMinutes: 10,
    co2SavedKg: 1.8,
    wheelchairAccessible: true,
    airConditioned: false,
    summary: 'Direct budget-friendly commute with comfortable non-stop flyover routing.',
    scheduleTimes: ['07:00 AM', '07:12 AM', '07:24 AM', '07:36 AM'],
    stops: [
      { id: 's30', name: 'Central Station Terminal', latitude: 28.6415, longitude: 77.2195, timeOffsetMinutes: 0, crowdLevel: 'low' },
      { id: 's31', name: 'Civil Lines Crossing', latitude: 28.6756, longitude: 77.2241, timeOffsetMinutes: 22, crowdLevel: 'low' },
      { id: 's32', name: 'Mall Road Junction', latitude: 28.6948, longitude: 77.2132, timeOffsetMinutes: 36, crowdLevel: 'low' },
      { id: 's33', name: 'University North Campus', latitude: 28.6892, longitude: 77.2104, timeOffsetMinutes: 45, crowdLevel: 'low' },
    ],
    segments: [
      {
        mode: 'walk',
        lineName: 'Walking',
        lineColor: '#10b981',
        fromStop: 'Central Station',
        toStop: 'Bus Stand Platform 7',
        durationMinutes: 6,
        distanceKm: 0.4,
        fare: 0,
        instructions: 'Walk to Bus Platform 7',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
      {
        mode: 'bus',
        lineName: 'City Express 500',
        lineColor: '#f59e0b',
        fromStop: 'Central Station Terminal',
        toStop: 'University North Campus',
        durationMinutes: 39,
        distanceKm: 17.8,
        fare: 20,
        instructions: 'Take Bus 500 direct to North Campus Main Gate.',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
    ],
    polylinePoints: [
      [28.6415, 77.2195],
      [28.6756, 77.2241],
      [28.6948, 77.2132],
      [28.6892, 77.2104],
    ],
  },
  {
    id: 'route-4',
    routeId: 'MTR-YEL-02',
    name: 'Metro Yellow Line (North-South Corridor)',
    transportType: 'metro',
    origin: 'Samaypur Badli',
    destination: 'Millennium City Centre',
    distance: 48.8,
    estimatedTime: 52,
    fare: 50,
    transfers: 0,
    walkingTime: 3,
    crowdLevel: 'high',
    status: 'delayed',
    delayMinutes: 8,
    frequencyMinutes: 3,
    co2SavedKg: 3.6,
    wheelchairAccessible: true,
    airConditioned: true,
    summary: 'High capacity arterial line connecting heritage hubs with southern tech business towers.',
    scheduleTimes: ['07:02 AM', '07:05 AM', '07:08 AM', '07:11 AM'],
    stops: [
      { id: 's40', name: 'Samaypur Badli', latitude: 28.7454, longitude: 77.1354, timeOffsetMinutes: 0, crowdLevel: 'low' },
      { id: 's41', name: 'Vishwa Vidyalaya', latitude: 28.6975, longitude: 77.2163, timeOffsetMinutes: 14, crowdLevel: 'moderate' },
      { id: 's42', name: 'Chandni Chowk', latitude: 28.6578, longitude: 77.2301, timeOffsetMinutes: 24, crowdLevel: 'high' },
      { id: 's43', name: 'Rajiv Chowk', latitude: 28.6328, longitude: 77.2195, timeOffsetMinutes: 30, crowdLevel: 'high', isInterchange: true },
      { id: 's44', name: 'AIIMS Medical Hub', latitude: 28.5672, longitude: 77.2100, timeOffsetMinutes: 40, crowdLevel: 'high' },
      { id: 's45', name: 'Millennium City Centre', latitude: 28.4595, longitude: 77.0725, timeOffsetMinutes: 52, crowdLevel: 'moderate' },
    ],
    segments: [
      {
        mode: 'metro',
        lineName: 'Yellow Line Direct',
        lineColor: '#eab308',
        fromStop: 'Samaypur Badli',
        toStop: 'Millennium City Centre',
        durationMinutes: 52,
        distanceKm: 48.8,
        fare: 50,
        instructions: 'Board Yellow Line heading towards Millennium City Centre.',
        crowdLevel: 'high',
        delayMinutes: 8,
      },
    ],
    polylinePoints: [
      [28.7454, 77.1354],
      [28.6975, 77.2163],
      [28.6578, 77.2301],
      [28.6328, 77.2195],
      [28.5672, 77.2100],
      [28.4595, 77.0725],
    ],
  },
  {
    id: 'route-5',
    routeId: 'TRN-SUB-03',
    name: 'Suburban Express Local (Western Corridors)',
    transportType: 'train',
    origin: 'Hazrat Nizamuddin Terminal',
    destination: 'Faridabad Industrial Hub',
    distance: 31.0,
    estimatedTime: 28,
    fare: 15,
    transfers: 0,
    walkingTime: 8,
    crowdLevel: 'moderate',
    status: 'on-time',
    delayMinutes: 0,
    frequencyMinutes: 15,
    co2SavedKg: 3.1,
    wheelchairAccessible: true,
    airConditioned: false,
    summary: 'Ultra-fast suburban heavy rail with minimal stops and lowest travel cost.',
    scheduleTimes: ['07:10 AM', '07:30 AM', '07:50 AM', '08:15 AM'],
    stops: [
      { id: 's50', name: 'Hazrat Nizamuddin Terminal', latitude: 28.5889, longitude: 77.2534, timeOffsetMinutes: 0, crowdLevel: 'moderate' },
      { id: 's51', name: 'Okhla Railway Junction', latitude: 28.5583, longitude: 77.2711, timeOffsetMinutes: 9, crowdLevel: 'moderate' },
      { id: 's52', name: 'Tughlakabad Station', latitude: 28.5083, longitude: 77.2917, timeOffsetMinutes: 18, crowdLevel: 'low' },
      { id: 's53', name: 'Faridabad Industrial Hub', latitude: 28.4111, longitude: 77.3125, timeOffsetMinutes: 28, crowdLevel: 'moderate' },
    ],
    segments: [
      {
        mode: 'train',
        lineName: 'EMU Suburban Train',
        lineColor: '#8b5cf6',
        fromStop: 'Hazrat Nizamuddin',
        toStop: 'Faridabad Industrial Hub',
        durationMinutes: 28,
        distanceKm: 31.0,
        fare: 15,
        instructions: 'Board Southern suburban local at Platform 3.',
        crowdLevel: 'moderate',
        delayMinutes: 0,
      },
    ],
    polylinePoints: [
      [28.5889, 77.2534],
      [28.5583, 77.2711],
      [28.5083, 77.2917],
      [28.4111, 77.3125],
    ],
  },
  {
    id: 'route-6',
    routeId: 'MTR-AIR-EXP',
    name: 'Orange Line (Airport High-Speed Express)',
    transportType: 'metro',
    origin: 'New Delhi Railway Station',
    destination: 'IGI Airport Terminal 3 / Aerocity',
    distance: 22.7,
    estimatedTime: 19,
    fare: 60,
    transfers: 0,
    walkingTime: 2,
    crowdLevel: 'low',
    status: 'on-time',
    delayMinutes: 0,
    frequencyMinutes: 8,
    co2SavedKg: 3.4,
    wheelchairAccessible: true,
    airConditioned: true,
    summary: 'Fastest transit corridor operating up to 120 km/h with in-flight style luggage check-in.',
    scheduleTimes: ['07:00 AM', '07:10 AM', '07:20 AM', '07:30 AM'],
    stops: [
      { id: 's60', name: 'New Delhi Railway Station', latitude: 28.6426, longitude: 77.2185, timeOffsetMinutes: 0, crowdLevel: 'moderate', isInterchange: true },
      { id: 's61', name: 'Shivaji Stadium', latitude: 28.6288, longitude: 77.2120, timeOffsetMinutes: 3, crowdLevel: 'low' },
      { id: 's62', name: 'Dhaula Kuan', latitude: 28.5919, longitude: 77.1610, timeOffsetMinutes: 9, crowdLevel: 'low', isInterchange: true },
      { id: 's63', name: 'Delhi Aerocity', latitude: 28.5489, longitude: 77.1205, timeOffsetMinutes: 15, crowdLevel: 'low' },
      { id: 's64', name: 'IGI Airport Terminal 3', latitude: 28.5562, longitude: 77.0863, timeOffsetMinutes: 19, crowdLevel: 'low' },
    ],
    segments: [
      {
        mode: 'metro',
        lineName: 'Airport Super Express',
        lineColor: '#ea580c',
        fromStop: 'New Delhi',
        toStop: 'IGI Airport Terminal 3',
        durationMinutes: 19,
        distanceKm: 22.7,
        fare: 60,
        instructions: 'Take Airport Express train direct to T3 departures.',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
    ],
    polylinePoints: [
      [28.6426, 77.2185],
      [28.6288, 77.2120],
      [28.5919, 77.1610],
      [28.5489, 77.1205],
      [28.5562, 77.0863],
    ],
  },
  {
    id: 'route-7',
    routeId: 'CAB-MET-SMART',
    name: 'Shared Auto-Taxi + Metro Magenta Link',
    transportType: 'mixed',
    origin: 'Sector 14 Residential Gate',
    destination: 'Cyber Tech Park',
    distance: 14.8,
    estimatedTime: 26,
    fare: 55,
    transfers: 1,
    walkingTime: 3,
    crowdLevel: 'low',
    status: 'on-time',
    delayMinutes: 0,
    frequencyMinutes: 5,
    co2SavedKg: 1.4,
    wheelchairAccessible: true,
    airConditioned: true,
    summary: 'First/last-mile first class connectivity with seamless smart cab sync.',
    scheduleTimes: ['Every 5 mins'],
    stops: [
      { id: 's70', name: 'Sector 14 Gate', latitude: 28.6139, longitude: 77.2090, timeOffsetMinutes: 0, crowdLevel: 'low' },
      { id: 's71', name: 'Hauz Khas Metro Interchange', latitude: 28.5434, longitude: 77.2064, timeOffsetMinutes: 8, crowdLevel: 'moderate', isInterchange: true },
      { id: 's72', name: 'Cyber Tech Park', latitude: 28.4595, longitude: 77.0266, timeOffsetMinutes: 26, crowdLevel: 'low' },
    ],
    segments: [
      {
        mode: 'taxi',
        lineName: 'Electric Auto Shuttle',
        lineColor: '#eab308',
        fromStop: 'Sector 14 Gate',
        toStop: 'Hauz Khas Metro Interchange',
        durationMinutes: 8,
        distanceKm: 3.2,
        fare: 25,
        instructions: 'Take pre-booked Electric Auto Shuttle to Hauz Khas Gate 2.',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
      {
        mode: 'metro',
        lineName: 'Magenta Line',
        lineColor: '#db2777',
        fromStop: 'Hauz Khas',
        toStop: 'Cyber Tech Park Station',
        durationMinutes: 18,
        distanceKm: 11.6,
        fare: 30,
        instructions: 'Board fast Magenta Line towards Cyber Tech Park.',
        crowdLevel: 'low',
        delayMinutes: 0,
      },
    ],
    polylinePoints: [
      [28.6139, 77.2090],
      [28.5434, 77.2064],
      [28.4595, 77.0266],
    ],
  },
];

export const INITIAL_TRANSIT_UPDATES = [
  {
    id: 'up-1',
    routeId: 'MTR-YEL-02',
    routeName: 'Metro Yellow Line',
    transportType: 'metro',
    delay: 8,
    crowdLevel: 'high',
    status: 'delayed',
    message: 'Signal calibration maintenance between Kashmere Gate and Rajiv Chowk causing 8-minute headway delays.',
    affectedStops: ['Kashmere Gate', 'Chandni Chowk', 'Rajiv Chowk'],
    severity: 'warning',
    expectedNextArrivalMinutes: 6,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'up-2',
    routeId: 'MXD-MTR-BUS-42',
    routeName: 'Bus Route 42 / Feeder',
    transportType: 'bus',
    delay: 5,
    crowdLevel: 'moderate',
    status: 'delayed',
    message: 'Peak hour road traffic near Ring Road Flyover causing minor 5 min delay.',
    affectedStops: ['Dhaula Kuan Hub', 'Moti Bagh'],
    severity: 'info',
    expectedNextArrivalMinutes: 4,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'up-3',
    routeId: 'MTR-BLU-01',
    routeName: 'Metro Blue Line',
    transportType: 'metro',
    delay: 0,
    crowdLevel: 'moderate',
    status: 'on-time',
    message: 'Operating normal peak-frequency service with air-conditioned 8-coach rakes every 3 minutes.',
    affectedStops: [],
    severity: 'info',
    expectedNextArrivalMinutes: 2,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'up-4',
    routeId: 'MTR-AIR-EXP',
    routeName: 'Airport Express Line',
    transportType: 'metro',
    delay: 0,
    crowdLevel: 'low',
    status: 'on-time',
    message: 'Optimal operation. Express transit to IGI Terminal 3 running seamlessly in 19 mins.',
    affectedStops: [],
    severity: 'info',
    expectedNextArrivalMinutes: 3,
    timestamp: new Date().toISOString(),
  },
  {
    id: 'up-5',
    routeId: 'BUS-EXP-500',
    routeName: 'City Express Bus 500',
    transportType: 'bus',
    delay: 0,
    crowdLevel: 'low',
    status: 'on-time',
    message: 'Dedicated bus lane active on North Corridor. Smooth journey times.',
    affectedStops: [],
    severity: 'info',
    expectedNextArrivalMinutes: 7,
    timestamp: new Date().toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'delay',
    title: 'Metro Yellow Line Delay Alert',
    message: 'Metro Yellow Line is experiencing 8-minute delays due to track maintenance near Rajiv Chowk.',
    routeId: 'MTR-YEL-02',
    severity: 'warning',
    read: false,
    actionUrl: '/live-transit',
    actionLabel: 'View Live Board',
    createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: 'notif-2',
    type: 'alternative',
    title: 'Faster Alternative Route Available',
    message: 'Take Metro Blue Line + Bus 42 to bypass Rajiv Chowk bottleneck and arrive 14 minutes earlier.',
    routeId: 'MXD-MTR-BUS-42',
    severity: 'success',
    read: false,
    actionUrl: '/routes?origin=Dwarka&destination=Cyber+City',
    actionLabel: 'Switch Route',
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    id: 'notif-3',
    type: 'crowd',
    title: 'Peak Crowd Advisory',
    message: 'Your saved Home → Office morning route has heavy crowding at Interchange 2. Recommended off-peak slot: 08:45 AM.',
    routeId: 'MTR-BLU-01',
    severity: 'info',
    read: true,
    actionUrl: '/saved-journeys',
    actionLabel: 'Check Route',
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'notif-4',
    type: 'system',
    title: 'Carbon Footprint Milestone! 🌱',
    message: 'Congratulations! You saved 18.4 kg CO2 this week by choosing smart public transit over private cars.',
    severity: 'success',
    read: true,
    actionUrl: '/analytics',
    actionLabel: 'View Analytics',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const INITIAL_SAVED_JOURNEYS = [
  {
    id: 'saved-1',
    name: 'Home → Cyber Tech Office',
    origin: 'Greenwood Heights, Sector 14',
    destination: 'Cyber Tech Park, Gate 3',
    preferredMode: 'metro',
    estimatedTime: 38,
    estimatedFare: 40,
    tags: ['Daily Commute', 'Morning Peak'],
    departureTimePreference: '08:30 AM',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'saved-2',
    name: 'Home → University North Campus',
    origin: 'Greenwood Heights, Sector 14',
    destination: 'University North Campus',
    preferredMode: 'bus',
    estimatedTime: 45,
    estimatedFare: 20,
    tags: ['College', 'Economy Route'],
    departureTimePreference: '09:15 AM',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'saved-3',
    name: 'Home → International Airport T3',
    origin: 'Greenwood Heights, Sector 14',
    destination: 'IGI Airport Terminal 3',
    preferredMode: 'metro',
    estimatedTime: 22,
    estimatedFare: 60,
    tags: ['Travel', 'Express'],
    departureTimePreference: '06:00 AM',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
  },
];

export const INITIAL_JOURNEY_HISTORY = [
  {
    id: 'hist-1',
    origin: 'Dwarka Sector 21',
    destination: 'Cyber City Hub',
    routeId: 'MXD-MTR-BUS-42',
    routeName: 'Metro Blue Line → Bus 42',
    transportType: 'mixed',
    travelTime: 36,
    fare: 35,
    crowdLevel: 'moderate',
    co2SavedKg: 2.4,
    status: 'completed',
    date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    id: 'hist-2',
    origin: 'Greenwood Heights',
    destination: 'University North Campus',
    routeId: 'BUS-EXP-500',
    routeName: 'City Express Bus 500',
    transportType: 'bus',
    travelTime: 42,
    fare: 20,
    crowdLevel: 'low',
    co2SavedKg: 1.8,
    status: 'completed',
    date: new Date(Date.now() - 1000 * 60 * 60 * 27).toISOString(),
  },
  {
    id: 'hist-3',
    origin: 'Central Station Terminal',
    destination: 'Faridabad Industrial Hub',
    routeId: 'TRN-SUB-03',
    routeName: 'Suburban Express Local',
    transportType: 'train',
    travelTime: 30,
    fare: 15,
    crowdLevel: 'moderate',
    co2SavedKg: 3.1,
    status: 'completed',
    date: new Date(Date.now() - 1000 * 60 * 60 * 50).toISOString(),
  },
  {
    id: 'hist-4',
    origin: 'New Delhi Railway Station',
    destination: 'IGI Airport Terminal 3',
    routeId: 'MTR-AIR-EXP',
    routeName: 'Airport High-Speed Express',
    transportType: 'metro',
    travelTime: 19,
    fare: 60,
    crowdLevel: 'low',
    co2SavedKg: 3.4,
    status: 'completed',
    date: new Date(Date.now() - 1000 * 60 * 60 * 75).toISOString(),
  },
  {
    id: 'hist-5',
    origin: 'Samaypur Badli',
    destination: 'Millennium City Centre',
    routeId: 'MTR-YEL-02',
    routeName: 'Metro Yellow Line',
    transportType: 'metro',
    travelTime: 58,
    fare: 50,
    crowdLevel: 'high',
    co2SavedKg: 3.5,
    status: 'completed',
    date: new Date(Date.now() - 1000 * 60 * 60 * 98).toISOString(),
  },
];

export const INITIAL_FEEDBACKS = [
  {
    id: 'fb-1',
    userName: 'Aarav Sharma',
    userEmail: 'aarav@example.com',
    routeId: 'MTR-BLU-01',
    routeName: 'Metro Blue Line (Rapid Transit)',
    rating: 5,
    crowdFeedback: 'moderate',
    delayFeedbackMinutes: 0,
    cleanlinessRating: 5,
    punctualityRating: 5,
    comment: 'Punctual, super clean and AC worked great during peak 38°C afternoon!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'fb-2',
    userName: 'Priya Patel',
    userEmail: 'priya@example.com',
    routeId: 'MXD-MTR-BUS-42',
    routeName: 'Metro + Bus 42 Feeder',
    rating: 4,
    crowdFeedback: 'low',
    delayFeedbackMinutes: 4,
    cleanlinessRating: 4,
    punctualityRating: 4,
    comment: 'The skywalk interchange is convenient and saved 10 minutes vs waiting in cab traffic.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
  },
  {
    id: 'fb-3',
    userName: 'Vikram Singh',
    userEmail: 'vikram@example.com',
    routeId: 'MTR-YEL-02',
    routeName: 'Metro Yellow Line',
    rating: 3,
    crowdFeedback: 'high',
    delayFeedbackMinutes: 8,
    cleanlinessRating: 4,
    punctualityRating: 3,
    comment: 'Very crowded at Rajiv Chowk platform 2. Assistant app warned me in time to take Blue line instead.',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
];

export const DEMO_USERS = [
  {
    id: 'user-commuter-01',
    name: 'Alex Commuter',
    email: 'commuter@smarttransit.com',
    passwordHash: '$2a$10$fQ7QnZgB3Qd1v4pT1Q3hE.mZ0nU2Zk0x/Y2hW9.1z4eE7m2hY6c6', // pass123
    role: 'user',
    homeLocation: {
      name: 'Greenwood Heights, Sector 14',
      latitude: 28.6139,
      longitude: 77.2090,
      address: 'Sector 14 Residential Zone',
    },
    workLocation: {
      name: 'Cyber Tech Park, Gate 3',
      latitude: 28.4595,
      longitude: 77.0266,
      address: 'Phase 2 Tech Zone',
    },
    collegeLocation: {
      name: 'University North Campus',
      latitude: 28.6892,
      longitude: 77.2104,
    },
    preferences: {
      preferredModes: ['metro', 'bus', 'walk'],
      maxTravelTime: 45,
      maxBudget: 60,
      preferFastest: true,
      preferCheapest: false,
      avoidCrowds: true,
      avoidTransfers: false,
      minimizeWalking: false,
      weightTime: 35,
      weightCost: 20,
      weightCrowd: 25,
      weightTransfers: 10,
      weightWalking: 10,
    },
  },
  {
    id: 'user-admin-01',
    name: 'Sarah Transit Admin',
    email: 'admin@smarttransit.com',
    passwordHash: '$2a$10$fQ7QnZgB3Qd1v4pT1Q3hE.mZ0nU2Zk0x/Y2hW9.1z4eE7m2hY6c6', // admin123
    role: 'admin',
    homeLocation: {
      name: 'City Central Station Area',
      latitude: 28.6415,
      longitude: 77.2195,
    },
    workLocation: {
      name: 'Transit Authority Command Center',
      latitude: 28.6258,
      longitude: 77.2343,
    },
    preferences: {
      preferredModes: ['metro', 'train', 'bus', 'taxi'],
      maxTravelTime: 90,
      maxBudget: 200,
      preferFastest: true,
      preferCheapest: false,
      avoidCrowds: false,
      avoidTransfers: false,
      minimizeWalking: false,
      weightTime: 30,
      weightCost: 20,
      weightCrowd: 20,
      weightTransfers: 15,
      weightWalking: 15,
    },
  },
];
